# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
